import type { Metadata } from "next";
import "./globals.css";

import { Albert_Sans, Montserrat_Alternates } from "next/font/google";
import logoImg from "@/public/Artboard1.png";

import Link from "next/link";
import RootLayoutProps from "@/types/types";
const albertsans = Albert_Sans({ subsets: ["latin"], display: "swap" });
const montserratalternates = Montserrat_Alternates({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-monsterrat-alternates",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${albertsans.className} ${montserratalternates.className}`}
      >
        <header className="p-2 flex justify-between items-center w-full">
          <Link href="/">
            <img
              src={logoImg.src}
              alt="as"
              width={logoImg.width}
              height={logoImg.height}
              className="cursor-pointer lg:w-auto w-30"
            />
          </Link>
          <div className="flex items-center gap-4 pr-4">
            <Link
              href="/3d-models"
              className="cursor-pointer p-1 border-b-2 border-amber-500 lg:text-xl text-xs"
            >
              3D MODELS
            </Link>
            <Link
              href="/about"
              className="cursor-pointer p-1 border-b-2 border-amber-500 lg:text-xl text-xs"
            >
              ABOUT
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
